-- MySQL Script generated by MySQL Workbench
-- Sun Feb 12 17:05:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `TPpessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPpessoa` ;

CREATE TABLE IF NOT EXISTS `TPpessoa` (
  `idTPpessoa` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pessoa` ;

CREATE TABLE IF NOT EXISTS `Pessoa` (
  `idPessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Datacriacao` DATE NOT NULL,
  `Nome fantasia` VARCHAR(45) NOT NULL,
  `Razaosocial` VARCHAR(45) NOT NULL,
  `IE_RG` INT NOT NULL,
  `CPF_CNPJ` INT NOT NULL,
  `Situacao` INT NOT NULL,
  `Telcomercial` INT NOT NULL,
  `Telresidencial` INT NOT NULL,
  `Celular` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPpessoa_Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPpessoa_Pessoa` ;

CREATE TABLE IF NOT EXISTS `TPpessoa_Pessoa` (
  `idTPpessoa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idTPpessoa`, `idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPendereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPendereco` ;

CREATE TABLE IF NOT EXISTS `TPendereco` (
  `idTPendereco` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

CREATE TABLE IF NOT EXISTS `Endereco` (
  `idEndereço` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTPendereco` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `Estado` VARCHAR(2) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `EnderecoPadrao` TINYINT NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grupo` ;

CREATE TABLE IF NOT EXISTS `Grupo` (
  `idGrupo` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subgrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subgrupo` ;

CREATE TABLE IF NOT EXISTS `Subgrupo` (
  `idSubgrupo` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empresa` ;

CREATE TABLE IF NOT EXISTS `Empresa` (
  `idEmpresa` INT NOT NULL,
  `Datadecriacao` DATE NOT NULL,
  `CRT` INT NOT NULL,
  `Nomefantasia` VARCHAR(45) NOT NULL,
  `Razaosocial` VARCHAR(45) NOT NULL,
  `CNPJ` INT NOT NULL,
  `inscricaoEstadual` INT NOT NULL,
  `inscricaoMunicipal` INT NOT NULL,
  `CEP` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grupo_Tributario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grupo_Tributario` ;

CREATE TABLE IF NOT EXISTS `Grupo_Tributario` (
  `idGrupo_Tributario` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrupo_Tributario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idSubgrupo` INT NOT NULL,
  `idGrupo_Tributario` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `UnidadedeMedida` VARCHAR(45) NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gradey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gradey` ;

CREATE TABLE IF NOT EXISTS `Gradey` (
  `idGradey` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGradey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gradex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gradex` ;

CREATE TABLE IF NOT EXISTS `Gradex` (
  `idGradex` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGradex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produtograde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produtograde` ;

CREATE TABLE IF NOT EXISTS `Produtograde` (
  `idProdutograde` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `idGradey` INT NOT NULL,
  `idGradex` INT NOT NULL,
  `Saldo` VARCHAR(45) NOT NULL,
  `CodigodeBarras` INT NOT NULL,
  `PesoBruto` DOUBLE NOT NULL,
  `PesoLiquido` DOUBLE NOT NULL,
  `ValordeVenda` DOUBLE NOT NULL,
  `CustoMedio` DOUBLE NOT NULL,
  `CustoAtual` DOUBLE NOT NULL,
  `EstoqueMinimo` DOUBLE NOT NULL,
  `EstoqueMaximo` DOUBLE NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProdutograde`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Localizacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Localizacao` ;

CREATE TABLE IF NOT EXISTS `Localizacao` (
  `idLocalizacao` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocalizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Promocao` ;

CREATE TABLE IF NOT EXISTS `Promocao` (
  `idPromocao` INT NOT NULL,
  `idProdutograde` INT NOT NULL,
  `PorcentagemMinima` DOUBLE NOT NULL,
  `PorcentagemMaxima` DOUBLE NOT NULL,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPMovimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPMovimento` ;

CREATE TABLE IF NOT EXISTS `TPMovimento` (
  `idTPMovimento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPMovimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Conta` ;

CREATE TABLE IF NOT EXISTS `Conta` (
  `idConta` INT NOT NULL,
  `Numero_Banco` VARCHAR(45) NOT NULL,
  `Agencia` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Numero_Conta` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanoDeContas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlanoDeContas` ;

CREATE TABLE IF NOT EXISTS `PlanoDeContas` (
  `idPlanoDeContas` INT NOT NULL,
  `Classificacao` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `idPlanoDeContasPai` INT NOT NULL,
  `idConta` INT NOT NULL,
  PRIMARY KEY (`idPlanoDeContas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPFinanceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPFinanceiro` ;

CREATE TABLE IF NOT EXISTS `TPFinanceiro` (
  `idTPFinanceiro` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPFinanceiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Operacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Operacao` ;

CREATE TABLE IF NOT EXISTS `Operacao` (
  `idOperacao` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Entrada/Saida` DOUBLE NOT NULL,
  `idPlanoDeContas` INT NOT NULL,
  `idTPFinanceiro` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  PRIMARY KEY (`idOperacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Operacao_Fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Operacao_Fiscal` ;

CREATE TABLE IF NOT EXISTS `Operacao_Fiscal` (
  `idOperacao_Fiscal` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Desc_CFOP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOperacao_Fiscal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movimento` ;

CREATE TABLE IF NOT EXISTS `Movimento` (
  `idMovimento` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTPMovimento` INT NOT NULL,
  `idOperacao` INT NOT NULL,
  `DataCadastro` DATE NOT NULL,
  `DataAlteracao` DATE NOT NULL,
  `Entregar(S/N)` TINYINT NOT NULL,
  `DataBaixa` DATE NOT NULL,
  `Desconto/acrescimo` DOUBLE NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idMovimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tributacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tributacao` ;

CREATE TABLE IF NOT EXISTS `Tributacao` (
  `idTributacao` INT NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  `idGrupo_Tributario` INT NOT NULL,
  `icms` VARCHAR(45) NOT NULL,
  `cfop` VARCHAR(45) NOT NULL,
  `csosn` VARCHAR(45) NOT NULL,
  `csticms` VARCHAR(45) NOT NULL,
  `icmsst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTributacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ItemMovimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItemMovimento` ;

CREATE TABLE IF NOT EXISTS `ItemMovimento` (
  `idItemMovimento` INT NOT NULL,
  `idProdutograde` INT NOT NULL,
  `idLocalizacao` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  `Promocao_idPromocao` INT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  `Saldoestoque` VARCHAR(45) NOT NULL,
  `Datacadastro` DATE NOT NULL,
  `Dataalteracao` DATE NOT NULL,
  `Valorunitario` DOUBLE NOT NULL,
  `DescontoAcrescimo` DOUBLE NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  `idTributacao` INT NOT NULL,
  PRIMARY KEY (`idItemMovimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPPagamento` ;

CREATE TABLE IF NOT EXISTS `TPPagamento` (
  `idTPPagamento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Conciliado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovimentoParcela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovimentoParcela` ;

CREATE TABLE IF NOT EXISTS `MovimentoParcela` (
  `idMovimentoParcelas` INT NOT NULL,
  `idTPPagamento` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idMovimentoParcelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Financeiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Financeiro` ;

CREATE TABLE IF NOT EXISTS `Financeiro` (
  `idFinanceiro` INT NOT NULL AUTO_INCREMENT,
  `idMovimentoParcelas` INT NOT NULL,
  `idTPFinanceiro` INT NOT NULL,
  `idPlanoDeContas` INT NOT NULL,
  `idTPPagamento` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `DTcadastro` DATE NOT NULL,
  `DTalteracao` DATE NOT NULL,
  `DTpagamento` DATE NOT NULL,
  `DTvencimento` DATE NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Valorpago` DOUBLE NOT NULL,
  `Desc_acresc` DOUBLE NOT NULL,
  `Nrparcela` INT NOT NULL,
  `Observacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFinanceiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movimento_Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movimento_Conta` ;

CREATE TABLE IF NOT EXISTS `Movimento_Conta` (
  `idMovimento_Conta` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` VARCHAR(45) NOT NULL,
  `Data_Baixa` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Data_Conciliacao` DATE NOT NULL,
  `Conciliado` VARCHAR(45) NOT NULL,
  `idConta` INT NOT NULL,
  PRIMARY KEY (`idMovimento_Conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Financeiro/CC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Financeiro/CC` ;

CREATE TABLE IF NOT EXISTS `Financeiro/CC` (
  `idMovimento_Conta` INT NOT NULL,
  `idFinanceiro` INT NOT NULL,
  PRIMARY KEY (`idMovimento_Conta`, `idFinanceiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPI` ;

CREATE TABLE IF NOT EXISTS `IPI` (
  `idIPI` INT NOT NULL AUTO_INCREMENT,
  `IPI` VARCHAR(45) NOT NULL,
  `CSTIPI` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idIPI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIS` ;

CREATE TABLE IF NOT EXISTS `PIS` (
  `idPIS` INT NOT NULL AUTO_INCREMENT,
  `PIS` VARCHAR(45) NOT NULL,
  `CSTPIS` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idPIS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cofins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cofins` ;

CREATE TABLE IF NOT EXISTS `Cofins` (
  `idCofins` INT NOT NULL AUTO_INCREMENT,
  `Cofins` VARCHAR(45) NOT NULL,
  `CSTCofins` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idCofins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nota` ;

CREATE TABLE IF NOT EXISTS `Nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `NRNota` VARCHAR(10) NOT NULL,
  `idMovimento` INT NOT NULL,
  `DataEmissao` DATETIME NULL,
  `Situacao` VARCHAR(8) NULL,
  PRIMARY KEY (`idNota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NotaItem` ;

CREATE TABLE IF NOT EXISTS `NotaItem` (
  `idNotaItem` INT NOT NULL,
  `idProdutoGrade` INT NOT NULL,
  `idNota` INT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  `Valorunitario` DOUBLE NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idNotaItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servico` ;

CREATE TABLE IF NOT EXISTS `Servico` (
  `idServico` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idSubgrupo` INT NOT NULL,
  `idGrupo_Tributario` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Situacao` VARCHAR(1) NOT NULL,
  `ValorServico` DECIMAL(8) NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ItemServico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItemServico` ;

CREATE TABLE IF NOT EXISTS `ItemServico` (
  `idItemServico` INT NOT NULL,
  `idServico` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  `Promocao_idPromocao` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Datacadastro` DATE NOT NULL,
  `Dataalteracao` DATE NOT NULL,
  `Valorunitario` DOUBLE NOT NULL,
  `DescontoAcrescimo` DOUBLE NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  `idTributacao` INT NOT NULL,
  `idItemMovimento` INT NULL,
  `idPrestador` INT NULL,
  PRIMARY KEY (`idItemServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrupoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GrupoUsuario` ;

CREATE TABLE IF NOT EXISTS `GrupoUsuario` (
  `idGrupoUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Situacao` INT NOT NULL,
  PRIMARY KEY (`idGrupoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Situacao` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `idGrupoUsuario` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Telas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Telas` ;

CREATE TABLE IF NOT EXISTS `Telas` (
  `idTela` INT NOT NULL,
  `NomeTela` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Permissao` ;

CREATE TABLE IF NOT EXISTS `Permissao` (
  `idPermissao` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idTela` INT NOT NULL,
  `ALTERACAO` TINYINT NOT NULL,
  `INCLUSAO` TINYINT NULL,
  `EXCLUSAO` TINYINT NULL,
  `CONSULTA` TINYINT NULL,
  PRIMARY KEY (`idPermissao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
