-- MySQL Script generated by MySQL Workbench
-- Sun Feb 12 15:20:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cofins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cofins` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Cofins` (
  `idCofins` INT NOT NULL AUTO_INCREMENT,
  `Cofins` VARCHAR(45) NOT NULL,
  `CSTCofins` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idCofins`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Cofins_Operacao_Fiscal1_idx` ON `mydb`.`Cofins` (`idOperacao_Fiscal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `idConta` INT NOT NULL,
  `Numero_Banco` VARCHAR(45) NOT NULL,
  `Agencia` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Numero_Conta` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConta`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `Datadecriacao` DATE NOT NULL,
  `CRT` INT NOT NULL,
  `Nomefantasia` VARCHAR(45) NOT NULL,
  `Razaosocial` VARCHAR(45) NOT NULL,
  `CNPJ` INT NOT NULL,
  `inscricaoEstadual` INT NOT NULL,
  `inscricaoMunicipal` INT NOT NULL,
  `CEP` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereço` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTPendereco` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `Estado` VARCHAR(2) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `EnderecoPadrao` TINYINT NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Endereco_TPendereco1_idx` ON `mydb`.`Endereco` (`idTPendereco` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Endereco_Pessoa1_idx` ON `mydb`.`Endereco` (`idPessoa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Financeiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Financeiro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Financeiro` (
  `idFinanceiro` INT NOT NULL AUTO_INCREMENT,
  `idMovimentoParcelas` INT NOT NULL,
  `idTPFinanceiro` INT NOT NULL,
  `idPlanoDeContas` INT NOT NULL,
  `idTPPagamento` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `DTcadastro` DATE NOT NULL,
  `DTalteracao` DATE NOT NULL,
  `DTpagamento` DATE NOT NULL,
  `DTvencimento` DATE NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Valorpago` DOUBLE NOT NULL,
  `Desc_acresc` DOUBLE NOT NULL,
  `Nrparcela` INT NOT NULL,
  `Observacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFinanceiro`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_MovimentoParcela1_idx` ON `mydb`.`Financeiro` (`idMovimentoParcelas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_TPFinanceiro1_idx` ON `mydb`.`Financeiro` (`idTPFinanceiro` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_PlanoDeContas1_idx` ON `mydb`.`Financeiro` (`idPlanoDeContas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_TPPagamento1_idx` ON `mydb`.`Financeiro` (`idTPPagamento` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_Empresa1_idx` ON `mydb`.`Financeiro` (`idEmpresa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Financeiro_Pessoa1_idx` ON `mydb`.`Financeiro` (`idPessoa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Financeiro/CC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Financeiro/CC` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Financeiro/CC` (
  `idMovimento_Conta` INT NOT NULL,
  `idFinanceiro` INT NOT NULL,
  PRIMARY KEY (`idMovimento_Conta`, `idFinanceiro`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Conta_has_Financeiro_Financeiro1_idx` ON `mydb`.`Financeiro/CC` (`idFinanceiro` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Conta_has_Financeiro_Movimento_Conta1_idx` ON `mydb`.`Financeiro/CC` (`idMovimento_Conta` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Gradex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gradex` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Gradex` (
  `idGradex` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGradex`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Gradey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gradey` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Gradey` (
  `idGradey` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGradey`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Grupo_Tributario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grupo_Tributario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo_Tributario` (
  `idGrupo_Tributario` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrupo_Tributario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Grupo_Tributario_Empresa1_idx` ON `mydb`.`Grupo_Tributario` (`idEmpresa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`IPI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IPI` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`IPI` (
  `idIPI` INT NOT NULL AUTO_INCREMENT,
  `IPI` VARCHAR(45) NOT NULL,
  `CSTIPI` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idIPI`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_IPI_Operacao_Fiscal1_idx` ON `mydb`.`IPI` (`idOperacao_Fiscal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ItemMovimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemMovimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ItemMovimento` (
  `idItemMovimento` INT NOT NULL,
  `idProdutograde` INT NOT NULL,
  `idLocalizacao` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  `Promocao_idPromocao` INT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  `Saldoestoque` VARCHAR(45) NOT NULL,
  `Datacadastro` DATE NOT NULL,
  `Dataalteracao` DATE NOT NULL,
  `Valorunitario` DOUBLE NOT NULL,
  `DescontoAcrescimo` DOUBLE NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  `idTributacao` INT NOT NULL,
  PRIMARY KEY (`idItemMovimento`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ItemMovimento_Produtograde1_idx` ON `mydb`.`ItemMovimento` (`idProdutograde` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ItemMovimento_Localizacao1_idx` ON `mydb`.`ItemMovimento` (`idLocalizacao` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ItemMovimento_Promocao1_idx` ON `mydb`.`ItemMovimento` (`Promocao_idPromocao` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ItemMovimento_Movimento1_idx` ON `mydb`.`ItemMovimento` (`idMovimento` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ItemMovimento_Tributacao1_idx` ON `mydb`.`ItemMovimento` (`idTributacao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Localizacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Localizacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Localizacao` (
  `idLocalizacao` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocalizacao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Movimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Movimento` (
  `idMovimento` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTPMovimento` INT NOT NULL,
  `idOperacao` INT NOT NULL,
  `DataCadastro` DATE NOT NULL,
  `DataAlteracao` DATE NOT NULL,
  `Entregar(S/N)` TINYINT NOT NULL,
  `DataBaixa` DATE NOT NULL,
  `Desconto/acrescimo` DOUBLE NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idMovimento`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Empresa1_idx` ON `mydb`.`Movimento` (`idEmpresa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_TPMovimento1_idx` ON `mydb`.`Movimento` (`idTPMovimento` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Pessoa1_idx` ON `mydb`.`Movimento` (`idPessoa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Operacao1_idx` ON `mydb`.`Movimento` (`idOperacao` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Operacao_Fiscal1_idx` ON `mydb`.`Movimento` (`idOperacao_Fiscal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`MovimentoParcela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MovimentoParcela` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`MovimentoParcela` (
  `idMovimentoParcelas` INT NOT NULL,
  `idTPPagamento` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idMovimentoParcelas`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_MovimentoParcela_TPPagamento1_idx` ON `mydb`.`MovimentoParcela` (`idTPPagamento` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_MovimentoParcela_Movimento1_idx` ON `mydb`.`MovimentoParcela` (`idMovimento` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Movimento_Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movimento_Conta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Movimento_Conta` (
  `idMovimento_Conta` INT NOT NULL AUTO_INCREMENT,
  `Data_Cadastro` VARCHAR(45) NOT NULL,
  `Data_Baixa` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Data_Conciliacao` DATE NOT NULL,
  `Conciliado` VARCHAR(45) NOT NULL,
  `idConta` INT NOT NULL,
  PRIMARY KEY (`idMovimento_Conta`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Movimento_Conta_Conta1_idx` ON `mydb`.`Movimento_Conta` (`idConta` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Operacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Operacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Operacao` (
  `idOperacao` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Entrada/Saida` DOUBLE NOT NULL,
  `idPlanoDeContas` INT NOT NULL,
  `idTPFinanceiro` INT NOT NULL,
  `idMovimento` INT NOT NULL,
  PRIMARY KEY (`idOperacao`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Operacao_PlanoDeContas1_idx` ON `mydb`.`Operacao` (`idPlanoDeContas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Operacao_TPFinanceiro1_idx` ON `mydb`.`Operacao` (`idTPFinanceiro` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Operacao_Movimento1_idx` ON `mydb`.`Operacao` (`idMovimento` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Operacao_Fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Operacao_Fiscal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Operacao_Fiscal` (
  `idOperacao_Fiscal` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Desc_CFOP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOperacao_Fiscal`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PIS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`PIS` (
  `idPIS` INT NOT NULL AUTO_INCREMENT,
  `PIS` VARCHAR(45) NOT NULL,
  `CSTPIS` VARCHAR(45) NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  PRIMARY KEY (`idPIS`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PIS_Operacao_Fiscal1_idx` ON `mydb`.`PIS` (`idOperacao_Fiscal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Datacriacao` DATE NOT NULL,
  `Nome fantasia` VARCHAR(45) NOT NULL,
  `Razaosocial` VARCHAR(45) NOT NULL,
  `IE_RG` INT NOT NULL,
  `CPF_CNPJ` INT NOT NULL,
  `Situacao` INT NOT NULL,
  `Telcomercial` INT NOT NULL,
  `Telresidencial` INT NOT NULL,
  `Celular` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PlanoDeContas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlanoDeContas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`PlanoDeContas` (
  `idPlanoDeContas` INT NOT NULL,
  `Classificacao` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `idPlanoDeContasPai` INT NOT NULL,
  `idConta` INT NOT NULL,
  PRIMARY KEY (`idPlanoDeContas`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PlanoDeContas_PlanoDeContas1_idx` ON `mydb`.`PlanoDeContas` (`idPlanoDeContasPai` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_PlanoDeContas_Conta1_idx` ON `mydb`.`PlanoDeContas` (`idConta` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idSubgrupo` INT NOT NULL,
  `idGrupo_Tributario` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `UnidadedeMedida` VARCHAR(45) NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Produto_Grupo1_idx` ON `mydb`.`Produto` (`idGrupo` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Produto_Subgrupo1_idx` ON `mydb`.`Produto` (`idSubgrupo` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Produto_Grupo_Tributario1_idx` ON `mydb`.`Produto` (`idGrupo_Tributario` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produtograde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtograde` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produtograde` (
  `idProdutograde` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `idGradey` INT NOT NULL,
  `idGradex` INT NOT NULL,
  `Saldo` VARCHAR(45) NOT NULL,
  `CodigodeBarras` INT NOT NULL,
  `PesoBruto` DOUBLE NOT NULL,
  `PesoLiquido` DOUBLE NOT NULL,
  `ValordeVenda` DOUBLE NOT NULL,
  `CustoMedio` DOUBLE NOT NULL,
  `CustoAtual` DOUBLE NOT NULL,
  `EstoqueMinimo` DOUBLE NOT NULL,
  `EstoqueMaximo` DOUBLE NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProdutograde`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Produtograde_Produto1_idx` ON `mydb`.`Produtograde` (`idProduto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Produtograde_Gradey1_idx` ON `mydb`.`Produtograde` (`idGradey` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Produtograde_Gradex1_idx` ON `mydb`.`Produtograde` (`idGradex` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Promocao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Promocao` (
  `idPromocao` INT NOT NULL,
  `idProdutograde` INT NOT NULL,
  `PorcentagemMinima` DOUBLE NOT NULL,
  `PorcentagemMaxima` DOUBLE NOT NULL,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPromocao`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Promocao_Produtograde1_idx` ON `mydb`.`Promocao` (`idProdutograde` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Subgrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subgrupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Subgrupo` (
  `idSubgrupo` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubgrupo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Subgrupo_Grupo1_idx` ON `mydb`.`Subgrupo` (`idGrupo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPFinanceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPFinanceiro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPFinanceiro` (
  `idTPFinanceiro` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPFinanceiro`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPMovimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPMovimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPMovimento` (
  `idTPMovimento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPMovimento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPPagamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPPagamento` (
  `idTPPagamento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Conciliado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPPagamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPendereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPendereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPendereco` (
  `idTPendereco` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPendereco`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPpessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPpessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPpessoa` (
  `idTPpessoa` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTPpessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TPpessoa_Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPpessoa_Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TPpessoa_Pessoa` (
  `idTPpessoa` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idTPpessoa`, `idPessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TPpessoa_has_Pessoa_Pessoa1_idx` ON `mydb`.`TPpessoa_Pessoa` (`idPessoa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TPpessoa_has_Pessoa_TPpessoa_idx` ON `mydb`.`TPpessoa_Pessoa` (`idTPpessoa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Tributacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tributacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Tributacao` (
  `idTributacao` INT NOT NULL,
  `idOperacao_Fiscal` INT NOT NULL,
  `idGrupo_Tributario` INT NOT NULL,
  `icms` VARCHAR(45) NOT NULL,
  `cfop` VARCHAR(45) NOT NULL,
  `csosn` VARCHAR(45) NOT NULL,
  `csticms` VARCHAR(45) NOT NULL,
  `icmsst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTributacao`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Tributacao_Operacao_Fiscal1_idx` ON `mydb`.`Tributacao` (`idOperacao_Fiscal` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Tributacao_Grupo_Tributario1_idx` ON `mydb`.`Tributacao` (`idGrupo_Tributario` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
